CREATE TABLE IF NOT EXISTS `cx_orderdesk_order` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(64) NULL,
  `provider_listing_id` VARCHAR(128) NOT NULL,
  `orderdesk_order_id` VARCHAR(64) NULL,
  `order_id` VARCHAR(128) NULL,
  `source_name` VARCHAR(128) NULL,
  `status` VARCHAR(128) NULL,
  `order_date` DATETIME NULL,
  `updated_date` DATETIME NULL,
  `customer_name` VARCHAR(255) NULL,
  `customer_email` VARCHAR(255) NULL,
  `customer_phone` VARCHAR(64) NULL,
  `ship_name` VARCHAR(255) NULL,
  `ship_company` VARCHAR(255) NULL,
  `ship_address1` VARCHAR(255) NULL,
  `ship_address2` VARCHAR(255) NULL,
  `ship_city` VARCHAR(128) NULL,
  `ship_state` VARCHAR(64) NULL,
  `ship_postal_code` VARCHAR(32) NULL,
  `ship_country` VARCHAR(64) NULL,
  `currency` VARCHAR(16) NULL,
  `order_total` DECIMAL(12, 2) NULL,
  `shipping_total` DECIMAL(12, 2) NULL,
  `tax_total` DECIMAL(12, 2) NULL,
  `discount_total` DECIMAL(12, 2) NULL,
  `item_count` INT NULL,
  `quantity_total` INT NULL,
  `items_json` LONGTEXT NULL,
  `raw_json` LONGTEXT NULL,
  `last_synced_at` DATETIME NULL,
  `owner` VARCHAR(64) NULL,
  `dept_id` BIGINT NULL,
  `create_by` VARCHAR(64) NULL,
  `create_time` DATETIME NULL,
  `update_by` VARCHAR(64) NULL,
  `update_time` DATETIME NULL,
  `del_flag` CHAR(1) NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cx_orderdesk_order_provider_listing_id` (`provider_listing_id`),
  KEY `idx_cx_orderdesk_order_orderdesk_id` (`orderdesk_order_id`),
  KEY `idx_cx_orderdesk_order_order_date` (`order_date`),
  KEY `idx_cx_orderdesk_order_updated_date` (`updated_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
